### ISSUE TITLE
Transfering to Julia-Embedded

### ISSUE THREAD

**Issue by aminya** [fapplin/Julia_On_Development_Boards#1]
Dear @fapplin,
Would you like to transfer your repository to Julia-Embedded? I would give you owner access.
https://github.com/Julia-Embedded

**Comment by fapplin** [comment]
Only if you are going to take it over. I haven't done anything with it in many many months.
Frank

======================================================================= 
The price of greatness is responsibility. - Winston Churchill 

    On Wednesday, November 6, 2019, 12:44:53 AM EST, Amin Yahyaabadi <notifications@github.com> wrote:  
 
 
Dear @fapplin,
Would you like to transfer your repository to Julia-Embedded? I would give you owner access.
https://github.com/Julia-Embedded

**Comment by aminya** [comment]
@fapplin 
Sure! The goal is to involve more developers, and so we all can contribute and improve things.
At any point, you will have access to change anything if you want to.
Thank you!

**Comment by aminya** [comment]
@fapplin You are now a member of the organization, you have access to transfer the repository

**Comment by aminya** [comment]
Follow this help if you have trouble transferring to Julia-Embedded:
https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization
